apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: fvl-angular-deployment
spec:
  selector:
    matchLabels:
      app: fvl-angular
  replicas: 2 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: fvl-angular
    spec:
      containers:
      - name: fvl-angular
        image: lichodev/fvl-angular
        ports:
        - containerPort: 80
