apiVersion: v1
kind: Service
metadata:
  name: fvl-angular-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: fvl-angular
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80